### PR TITLE
Nx vite preview server

### PR DESCRIPTION
**Pull request by thijslimmen**

### CODE REVIEW

**Comment by thijslimmen** [comment]
#53

**Comment by sampullman** [comment]
Thanks! Do you think it's reasonable to reuse `customLogger.ts` from the dev-server executor?

I don't see any other issues with this and should be able to test/merge by tomorrow.

**Comment by thijslimmen** [comment]
Yes, could do that, just like the utils class being shared

**Comment by sampullman** [comment]
Thanks! It looks like the executor description is missing from `packages/vue3-vite/executors.json`, you can add:
```json
    "preview-server": {
      "implementation": "./src/executors/preview-server/executor",
      "schema": "./src/executors/preview-server/schema.json",
      "description": "preview server executor"
    },
```

I'm not sure if I've configured everything correctly, but the executor doesn't appear to be correctly serving the preview in the project I tested it in.

I've added the target:
```json
      "preview": {
          "executor": "nx-vue3-vite:preview-server",
          "options": {
            "port": 8090,
            "dist": "dist/apps/web"
          }
        },
```

and `nx run web:preview` appears to have started correctly, but the site does not load (it displays `Cannot GET /`). It's likely a path issue, but I haven't dug into the executor code yet.

**Comment by thijslimmen** [comment]
I have the following project setup:

apps/
   web/
libs/
dist/
  apps/
     web/
     
For my project I have to reference dist like this: ../../dist/apps/web

Perhaps we need to add some code to check if the dist option is an existing dist folder?

**Comment by sampullman** [comment]
That's odd, the project I tested it on has basically the same folder structure. I'll try to figure out what's going on when I have a moment.

**Comment by sampullman** [comment]
Closing, added some refactoring in #56

**Pull request closed without merging**
